### Day 67 of Python Programming

## Introduction to NumPy
### 1. What is NumPy?
NumPy is a Python library for numerical computing. It provides high-performance, multidimensional arrays and tools to work with them. It is particularly useful for scientific computing and data analysis.

### 2. Installing NumPy

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### 3. Creating Arrays

In [4]:
# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# 2D Array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# 3D Array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", array_3d)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Explanation:

Arrays can be one-dimensional, two-dimensional, or multi-dimensional. Use np.array() to create them.

### 4. Array Attributes

In [5]:
print("Shape of 2D Array:", array_2d.shape)  # Rows and columns
print("Number of Dimensions:", array_2d.ndim)  # 2D
print("Data Type:", array_2d.dtype)  # Data type of elements
print("Size of Array:", array_2d.size)  # Total elements


Shape of 2D Array: (2, 3)
Number of Dimensions: 2
Data Type: int32
Size of Array: 6


#### Explanation:
These attributes give metadata about the array, such as its dimensions, size, and element type.

#### 5. Array Initialization

In [6]:
# Array of zeros
zeros_array = np.zeros((3, 3))
print("Zeros Array:\n", zeros_array)

# Array of ones
ones_array = np.ones((2, 4))
print("Ones Array:\n", ones_array)

# Range of values
range_array = np.arange(10, 20, 2)
print("Range Array:", range_array)

# Evenly spaced numbers
linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_array)

# Random numbers
random_array = np.random.random((2, 3))
print("Random Array:\n", random_array)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range Array: [10 12 14 16 18]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Random Array:
 [[0.81221318 0.64431393 0.28758765]
 [0.98056196 0.9312944  0.08630874]]


### Explanation:

np.zeros() and np.ones() create arrays of zeros and ones, respectively.

np.arange() generates values with a step.

np.linspace() creates evenly spaced numbers over a range.

np.random.random() generates random numbers.

### 6. Indexing and Slicing

In [8]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing an element
print("Element at [1,2]:", array[1, 2])

# Row slicing
print("First row:", array[0, :])

# Column slicing
print("Second column:", array[:, 1])

# Submatrix
print("Submatrix:\n", array[0:2, 1:3])


Element at [1,2]: 6
First row: [1 2 3]
Second column: [2 5 8]
Submatrix:
 [[2 3]
 [5 6]]


#### Explanation:

Use square brackets [] to access elements.

: is used to specify ranges for slicing rows and columns

### 7. Basic Operations

In [9]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", array1 + array2)
print("Multiplication:", array1 * array2)

# Scalar operations
print("Multiply by 2:", array1 * 2)

# Comparison
print("Comparison (array1 > 2):", array1 > 2)


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Multiply by 2: [2 4 6]
Comparison (array1 > 2): [False False  True]


#### Explanation:

Arithmetic operations are element-wise.

Scalars are applied to all elements in the array.

#### 8. Aggregations

In [11]:
array = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard Deviation:", np.std(array))
print("Max value:", np.max(array))


Sum: 15
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Max value: 5


### Practice Questions

Create a 1D array of integers from 0 to 19.

Create a 3x3 matrix of ones and multiply it by 5.

Create a random array of 10 elements and find its mean and standard deviation.

Slice a 5x5 matrix to extract a 3x3 submatrix from its center.