#### Day 68 of Python Programming

### Advanced NumPy Operations

### 1. Reshaping Arrays

In [1]:
import numpy as np

In [2]:
# Reshaping a 1D array to 2D
array_1d = np.arange(1, 13)
array_2d = array_1d.reshape(3, 4)
print("Original 1D Array:", array_1d)
print("Reshaped to 2D (3x4):\n", array_2d)

# Flattening a 2D array to 1D
flattened = array_2d.ravel()
print("Flattened Array:", flattened)


Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 2D (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


#### Explanation:

reshape() changes the dimensions of an array. The total number of elements must remain constant.

ravel() flattens a multi-dimensional array into a 1D array.

#### 2. Broadcasting

In [3]:
# Adding a 1D array to each row of a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row = np.array([10, 20, 30])
result = matrix + row
print("Original Matrix:\n", matrix)
print("Row to Add:", row)
print("Result after Broadcasting:\n", result)


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row to Add: [10 20 30]
Result after Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### 3. Matrix Multiplication

In [4]:
# Element-wise multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
element_wise = A * B
print("Element-wise Multiplication:\n", element_wise)

# Matrix multiplication
matrix_mult = np.dot(A, B)  # or A @ B
print("Matrix Multiplication:\n", matrix_mult)


Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


#### Explanation:

Use * for element-wise multiplication and np.dot() or @ for matrix multiplication.

### 4. Sorting and Searching

In [5]:
array = np.array([25, 10, 35, 5, 20])

# Sorting
sorted_array = np.sort(array)
print("Sorted Array:", sorted_array)

# Searching
indices = np.where(array > 15)
print("Indices where elements > 15:", indices)


Sorted Array: [ 5 10 20 25 35]
Indices where elements > 15: (array([0, 2, 4], dtype=int64),)


### Explanation:

np.sort() sorts an array.

np.where() finds indices of elements that satisfy a condition.

### 5 Stacking and Splitting

In [7]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Vertical stacking
vstacked = np.vstack((A, B))
print("Vertical Stack:\n", vstacked)

# Horizontal stacking
hstacked = np.hstack((A, B))
print("Horizontal Stack:", hstacked)

# Splitting
split_arrays = np.split(hstacked, 2)
print("Split Arrays:", split_arrays)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]
Split Arrays: [array([1, 2, 3]), array([4, 5, 6])]


#### Explanation:

vstack() stacks arrays vertically, while hstack() stacks them horizontally.

split() divides an array into multiple parts.


#### Practice Questions
Create a 4x4 matrix and reshape it into a 2x8 matrix.

Use broadcasting to add a 1D array to each row of a 2D array.

Create a 3x3 matrix and find its determinant and inverse.

Save a NumPy array to a file and load it back into your program.